export const sampleUsers = [
  {
    UserID: 1,
    FirstName: 'Taulant',
    LastName: 'Culi',
    Email: "t.culi91@gmail.com",
    Password: "WE4Gyy3fKY;]9&NW",
    RoleID: 1
  }
];

export const users = [
  {
    UserID: 1,
    FirstName: 'Taulant',
    LastName: 'Culi',
    Email: "t.culi91@gmail.com",
    Password: "WE4Gyy3fKY;]9&NW",
    RoleID: 1
  }, {
    UserID: 2,
    FirstName: "Ewan",
    LastName: "Diament",
    Email: "ediament1@umn.edu",
    Password: "tCbIlyO",
    RoleID: 2
  }, {
    UserID: 3,
    FirstName: "Rodger",
    LastName: "Rumble",
    Email: "rrumble2@constantcontact.com",
    Password: "dm0YFASl1vW",
    RoleID: 3
  }, {
    UserID: 4,
    FirstName: "Willyt",
    LastName: "Waine",
    Email: "wwaine3@patch.com",
    Password: "D4phi1l",
    RoleID: 2
  }, {
    UserID: 5,
    FirstName: "Vassili",
    LastName: "Seekings",
    Email: "vseekings4@i2i.jp",
    Password: "PhONwZagF",
    RoleID: 1
  }, {
    UserID: 6,
    FirstName: "Wittie",
    LastName: "Bellam",
    Email: "wbellam5@biglobe.ne.jp",
    Password: "ewGqRy1rGxY",
    RoleID: 3
  }, {
    UserID: 7,
    FirstName: "Giles",
    LastName: "Arling",
    Email: "garling6@timesonline.co.uk",
    Password: "pHauJfO",
    RoleID: 2
  }, {
    UserID: 8,
    FirstName: "Ashil",
    LastName: "Duddle",
    Email: "aduddle7@linkedin.com",
    Password: "Ozi6baEq",
    RoleID: 3
  }, {
    UserID: 9,
    FirstName: "Amelia",
    LastName: "Mustoo",
    Email: "amustoo8@constantcontact.com",
    Password: "Imktd6RCc",
    RoleID: 1
  }, {
    UserID: 10,
    FirstName: "Abby",
    LastName: "Balls",
    Email: "aballs9@msn.com",
    Password: "UqnUt6USEVV",
    RoleID: 2
  }, {
    UserID: 11,
    FirstName: "Nalani",
    LastName: "Macilhench",
    Email: "nmacilhencha@wsj.com",
    Password: "7fJm31ldU",
    RoleID: 3
  }, {
    UserID: 12,
    FirstName: "Livia",
    LastName: "Andrea",
    Email: "landreab@mayoclinic.com",
    Password: "yayl8WdlX4",
    RoleID: 3
  }, {
    UserID: 13,
    FirstName: "Guido",
    LastName: "Niece",
    Email: "gniecec@auda.org.au",
    Password: "CSqw6Fd9HF",
    RoleID: 2
  }, {
    UserID: 14,
    FirstName: "Elaina",
    LastName: "de Cullip",
    Email: "edecullipd@cornell.edu",
    Password: "LCUQe8Xpkd4V",
    RoleID: 2
  }, {
    UserID: 15,
    FirstName: "Winfield",
    LastName: "Jopke",
    Email: "wjopkee@mayoclinic.com",
    Password: "0xFN097yu43S",
    RoleID: 1
  }, {
    UserID: 16,
    FirstName: "Jake",
    LastName: "Swaddle",
    Email: "jswaddlef@mozilla.com",
    Password: "kKUkrM",
    RoleID: 2
  }, {
    UserID: 17,
    FirstName: "Thea",
    LastName: "Hounsome",
    Email: "thounsomeg@opera.com",
    Password: "JLZeOW9CH66",
    RoleID: 3
  }, {
    UserID: 18,
    FirstName: "Melisenda",
     LastName: "Hayhow",
    Email: "mhayhowh@mashable.com",
    Password: "kFvpUIGa7L5",
    RoleID: 3
  }, {
    UserID: 19,
    FirstName: "Kit",
    LastName: "Wedmore.",
    Email: "kwedmorei@fastcompany.com",
    Password: "8ZupUrGNMR",
    RoleID: 3
  }, {
    UserID: 20,
    FirstName: "Teddie",
    LastName: "Glidder",
    Email: "tglidderj@mysql.com",
    Password: "oyoJabaQZh",
    RoleID: 2
  }
];
